# Generated by Django 4.2.5 on 2023-10-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipamento",
                    models.CharField(
                        max_length=255, verbose_name="Nome do Equipamento"
                    ),
                ),
                ("ca", models.CharField(max_length=20, verbose_name="Número do CA")),
                ("dataDeValidade", models.DateField(verbose_name="Data de Validade")),
                (
                    "situacao",
                    models.CharField(
                        max_length=100, verbose_name="Situação (Aprovado ou Vencido)"
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantidade em Estoque"
                    ),
                ),
                (
                    "aprovadoPara",
                    models.CharField(
                        max_length=255, verbose_name="Situação/Ambiente Adequado"
                    ),
                ),
                (
                    "marcacao",
                    models.CharField(
                        max_length=100, verbose_name="Onde Está Escrito o CA"
                    ),
                ),
                (
                    "natureza",
                    models.CharField(
                        max_length=100, verbose_name="Natureza (Nacional ou Importado)"
                    ),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
                ("Tamanho", models.CharField(max_length=50)),
                ("nProcesso", models.CharField(max_length=50, null=True)),
                ("nDoLaudo", models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
