# Generated by Django 4.2.4 on 2023-09-14 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_produtoepi_quantidade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdutoEPI',
            new_name='Produto',
        ),
    ]
