# Generated by Django 4.2.4 on 2023-09-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_rename_produtoepi_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='PossuiCA',
            field=models.BooleanField(default=True, verbose_name='Possui CA'),
        ),
    ]
